name: Bundle Size Check

on:
  pull_request:
    branches: [main, develop]

jobs:
  size:
    name: Check Bundle Size
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Analyze bundle size
        run: |
          echo "## Bundle Size Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Main Bundle" >> $GITHUB_STEP_SUMMARY
          ls -lh dist/assets/*.js | awk '{print "- " $9 ": " $5}' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### CSS Files" >> $GITHUB_STEP_SUMMARY
          ls -lh dist/assets/*.css | awk '{print "- " $9 ": " $5}' >> $GITHUB_STEP_SUMMARY

      - name: Check bundle size threshold
        run: |
          MAIN_BUNDLE_SIZE=$(find dist/assets -name 'index-*.js' -exec stat -f%z {} \;)
          MAX_SIZE=600000  # 600 KB threshold
          
          if [ $MAIN_BUNDLE_SIZE -gt $MAX_SIZE ]; then
            echo "::error::Main bundle size ($MAIN_BUNDLE_SIZE bytes) exceeds threshold ($MAX_SIZE bytes)"
            exit 1
          fi
          
          echo "✅ Bundle size OK: $MAIN_BUNDLE_SIZE bytes (threshold: $MAX_SIZE bytes)"
